@startuml 02-ContainerDiagram
!include <C4/C4_Container>

/' Level 2: Container diagram
   A container is something like a server-side web application, single-page application, desktop application,
   mobile app, database schema, file system, etc.
   Essentially, a container is a separately runnable/deployable unit (e.g. a separate process space)
   that executes code or stores data.
'/

title "Container Diagram for Wallet Service"

AddElementTag("microService", $shape=EightSidedShape(), $legendText="Microservice")
AddElementTag("storage", $shape=RoundedBoxShape(), $legendText="Storage")

LAYOUT_LEFT_RIGHT()

Person(user, "User", "A person managing their wallet")

System_Boundary(walletservice_boundary, "Wallet Service") {
    Container(walletapi, "Wallet API", "Spring Boot, Java", "Manages wallets and transactions", $tags = "microService")
    ContainerDb(database, "Database", "H2", "Stores wallet and transaction data", $tags = "storage")
}

Rel(user, walletapi, "Interacts with via REST API", "HTTPS")
Rel(walletapi, database, "Reads from and writes to", "JDBC")

Lay_R(walletapi, database)

LAYOUT_WITH_LEGEND()

@enduml
