name: Diagrams Generation

on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/diagrams-generation.yml'
      - 'docs/c4-model/*.puml'
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

env:
  IGNORE_GIT_HOOKS: true

jobs:
  diagrams-generation:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          ref: main
          persist-credentials: true
          fetch-depth: 0

      - name: Setup Java [v25]
        uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 # v4.8.0
        with:
          distribution: 'temurin'
          java-version: '25'

      - name: Install Dependencies
        run: |
          sudo apt install -y graphviz

      - name: Download PlantUML
        run: |
          PLANTUML_URL="${PLANTUML_URL:-https://github.com/plantuml/plantuml/releases/latest/download/plantuml.jar}"
          sudo curl -L "${PLANTUML_URL}" -o /usr/local/bin/plantuml.jar 
          sudo chmod +x /usr/local/bin/plantuml.jar
          sudo chown root:$(whoami) /usr/local/bin/plantuml.jar

      - name: Generate Diagrams
        run: |
          mkdir -p ./docs/diagrams
          java -jar /usr/local/bin/plantuml.jar -tpng -o "$(pwd)/docs/diagrams" "docs/c4-model/*.puml"

      - name: Check for changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "SHOULD_I_COMMIT=Yes" >> $GITHUB_ENV
          else
            echo "SHOULD_I_COMMIT=No" >> $GITHUB_ENV
          fi

      - name: Commit the changes
        if: ${{ env.SHOULD_I_COMMIT == 'Yes' }}
        run: |
          git config advice.ignoredHook false
          git config pull.rebase false
          git config --local user.email "action@github.com"
          git config --local user.name "C4 Model Diagrams Generation"
          git add --all
          git commit -m "doc(diagrams): update diagrams"
          git pull origin main

      - name: Push the changes
        if: ${{ env.SHOULD_I_COMMIT == 'Yes' }}
        uses: ad-m/github-push-action@4cc74773234f74829a8c21bc4d69dd4be9cfa599 # v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main

      - name: Setup Pages
        uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5.0.0

      - name: Upload artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
        with:
          path: './docs'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5

      - name: Environment Teardown
        if: always()
        run: |
          echo "Environment teardown"
